// Code generated by hertztool. DO NOT EDIT.

package main

import (
	"code.byted.org/middleware/hertz/pkg/app/server"

	"code.byted.org/bytefaas/bytefaas_native_hertz_a2a_deep_agent_demo/biz/handler"
)

// register register routes based on the IDL 'api.${HTTP Method}' annotation.
func register(r *server.Hertz) {
	customizeRegister(r)

	r.GET("/ping", handler.Ping)
}
