// Code generated by hertztool. DO NOT EDIT.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
)

// register register routes based on the IDL 'api.${HTTP Method}' annotation.
func register(r *server.Hertz) {
	customizeRegister(r)
}
