// Code generated by hertztool. DO NOT EDIT.

package debug

func init() {
	debugServer = &DebugServer{
		idlMap: make(map[string]string),
	}

	curVersion := "v1.1.2"
	if curVersion != "" {
		debugServer.SetHertztoolVersion(curVersion)
	}
	psm := "toutiao.bytefaas.native_hertz_a2a-deep-agent-demo"
	if psm != "" {
		debugServer.SetPsm(psm)
	}

}
