// Code generated by hertztool. DO NOT EDIT.

package debug

import (
	"bytes"
	"encoding/json"
	"net/http"

	"code.byted.org/middleware/hertz/byted/debug"
)

type ThriftFiles struct {
	PSM   string
	Files map[string]string
}

type ServerInfo struct {
	Server []ThriftFiles
}

type DebugServer struct {
	psm              string
	idlMap           map[string]string
	hertztoolVersion string
	rootTree         string //json格式表示idl解析结构
}

var debugServer *DebugServer

func StartDebugServer() {
	debug.RegisterDebugHandler("/runtime/hertztool", getRuntimeInfo)
}

func (s *DebugServer) SetIDL(fname, content string) {
	s.idlMap[fname] = content
}

func (s *DebugServer) SetPsm(psm string) {
	s.psm = psm
}

func (s *DebugServer) SetHertztoolVersion(version string) {
	s.hertztoolVersion = version
}

func (s *DebugServer) SetRootTree(rootTree string) {
	s.rootTree = rootTree
}

func getRuntimeInfo(resp http.ResponseWriter, request *http.Request) {
	resp.WriteHeader(200)
	thriftFiles := ThriftFiles{
		PSM:   debugServer.psm,
		Files: debugServer.idlMap,
	}
	serverInfo := &ServerInfo{
		Server: []ThriftFiles{
			thriftFiles,
		},
	}
	respData, _ := json.Marshal(serverInfo)
	var out bytes.Buffer
	json.Indent(&out, respData, "", "\t")
	resp.Write(out.Bytes())
}
