// Code generated by hertztool.

package handler

import (
	"code.byted.org/middleware/hertz/pkg/app"
	"code.byted.org/middleware/hertz/pkg/common/utils"
	"context"
)

func Ping(ctx context.Context, c *app.RequestContext) {
	c.JSON(200, utils.H{
		"message": "hey yo!",
	})
}

func HelloWorld(ctx context.Context, c *app.RequestContext) {
	c.JSON(200, utils.H{
		"message": "Hello World From Hertz @ FaaS-Native",
	})
}
